
--
-- Postgres SQL Schema dump automatic generated by geni
--


-- TABLES 

CREATE TABLE schema_migrations (
 id character varying (255) NOT NULL
);

CREATE TABLE subscriptions (
 id uuid  NOT NULL,
 email text  NOT NULL,
 name text  NOT NULL,
 subscribed_at timestamp with time zone  NOT NULL
);

-- CONSTRAINTS 

ALTER TABLE schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (id);

ALTER TABLE subscriptions ADD CONSTRAINT subscriptions_email_key UNIQUE (email);

ALTER TABLE subscriptions ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);

-- INDEXES 

CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (id)

CREATE UNIQUE INDEX subscriptions_email_key ON public.subscriptions USING btree (email)

CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id)

